### ISSUE TITLE
channels hang when stream raises exception

### ISSUE THREAD

**Issue by edwintorok** [mirage/ocaml-conduit#107]
When a body stream raises an exception the connection is kept open (probably forever).

Since the headers were already sent we don't have much choice but to close the channel, with chunked encoding `curl` would report a proper error then:

```
curl: (18) transfer closed with outstanding read data remaining
```

I was testing a fix like this

``` ocaml
-    Lwt.ignore_result (Lwt.pick events >>= fun () -> close (ic,oc))
+    Lwt.finalize (fun () -> Lwt.pick events) (fun () -> close (ic,oc)) |>
+    Lwt.ignore_result
```

Not sure if `Lwt.finalize` or `Lwt.on_termination` would be preferred here (finalize creates an extra closure?).

**Comment by dinosaure** [comment]
I'm not sure that `conduit.3.0.0` properly fix the error when it's mostly about the _tcp implementation_ used (which is not the part of the `conduit` package). If such error still exists, it's about `conduit-lwt` and the sub-module `Conduit_lwt.TCP` which implements the TCP protocol. As far as I can (and as the main developer of this impl.), I did not notice such behavior on my tests - but I did not test this specific issue.

Due to the major release, I will close this issue but if the bug re-appear, feel free to re-open the issue and I will try to investigate the bug more deeply.

**Comment by mseri** [comment]
I think this is still present in the rever to cohttp 4.0
