### ISSUE TITLE
rename mirage-conduit into conduit-mirage

### ISSUE THREAD

**Issue by samoht** [mirage/ocaml-conduit#231]
Not sure why this is in reverse vs. all other `conduit-*` package names.

**Comment by avsm** [comment]
because this is what it was before -- I wanted to leave the package names as similar as possible and then make all the changes in one go across various projects (e.g. mirage-http, mirage-conduit, mirage-dns) and to clearly deprecate the old packages to avoid confusion.  I'm still confused by tar-format->tar and git-mirage, since the older packages are still around.

**Comment by samoht** [comment]
I think removing the names which doesn't follow the convention would remove the confusion :-)

But yes, I guess it's ok to do that progressively!

**Comment by avsm** [comment]
but we can just delete the old packages -- they are still in opam-repository and show up in searches. So we do need some mechanism (e.g. `messages`) of deprecating them and/or edit the short descriptions to reflect that they were part of MirageOS2 or something...

**Comment by avsm** [comment]
for example try `opam list --depends-on mirage-unix` and try to figure out which of those packages are still relevant :)

**Comment by samoht** [comment]
Duplicate of #178
