### ISSUE TITLE
conduit-lwt-unix does not depend correctly on lwt_ssl (?)

### ISSUE THREAD

**Issue by aantron** [mirage/ocaml-conduit#237]
This caused problems in https://stackoverflow.com/questions/45772012/how-to-use-ocamls-cohttp-library-to-make-a-https-request

`conduit-lwt-unix` appears to use the presence of `lwt_ssl` to configure itself with SSL support: https://github.com/mirage/ocaml-conduit/blob/d29efc9a526cfb701f2eba271516b64ca0d918ce/lwt-unix/jbuild#L12-L17

<br/>

Meanwhile, `conduit-lwt-unix.opam` depends optionally only on `ssl`: https://github.com/mirage/ocaml-conduit/blob/d29efc9a526cfb701f2eba271516b64ca0d918ce/conduit-lwt-unix.opam#L22-L26

I think it should depend on `lwt_ssl` instead.

<br/>

**Comment by hcarty** [comment]
This seems correct. It should be a one line change to the opam file and a matching update to opam-repository.

**Comment by aantron** [comment]
It may also not be intuitive that one needs to install `lwt_ssl`, not just `ssl`. Maybe an `opam` file message in `conduit` or `cohttp` is good for fixing that. Just a suggestion.

**Comment by cdepillabout** [comment]
A note in the cohttp README would be helpful as well.

**Comment by dinosaure** [comment]
On this specific behavior, we decided to explicitly show on what `conduit` depends now and we deleted with the new version of `conduit` any `depopts` (a long retrospective on the MirageOS ecosystem showed to us that it's not the best to do). Due to this major update, we can consider this issue as close.

You must explicitly choose between `conduit-lwt-ssl` or `conduit-lwt-tls` now.

Thanks for your report.
