### ISSUE TITLE
No way to stop a server that hasn't started yet

### ISSUE THREAD

**Issue by rixed** [mirage/ocaml-conduit#273]
I have a server that fail in a loop because the TCP port is already bound.
I'm trying to stop this server, either by:
1. `Lwt.cancel` the thread  (actually the thread returned by Cohttp.Server.create);
2. `raise Exit` from the `on_exn` callback;
3. calling the `stop` thread.
to no avail.

Is there any way to interrupt a server in this state?

**Comment by dinosaure** [comment]
Not sure to really understand your issue but if a port is already used by someone else, the new version of `conduit` will just fail to initialize the _server_. I mean, if you do:

```ocaml
let tcp_config =
  { Conduit_lwt.TCP.sockaddr= Unix.(ADDR_INET (inet_addr_of_loopback, 8080))
  ; capacity= 40 }
let run =
  Conduit_lwt.Service.init tcp_config ~service:Conduit_lwt.TCP.service >>= function
  | Ok socket -> ...
  | Error err ->...
```

You will get an `Error (`Msg "Address 127.0.0.1 already in use")`, see this part of `conduit-lwt`:
https://github.com/mirage/ocaml-conduit/blob/66fd34a9dc1dc2507f6c20752e589ae53cc4ccf8/src/lwt/conduit_lwt.ml#L156-L192

So, I consider that your issue is fixed by the new version of `conduit`. If you have any troubles, feel free to re-open the issue. Thanks!

**Comment by rixed** [comment]
That's likely the case that a more recent version of conduit fixes this bug, indeed.
