### ISSUE TITLE
Up-to-date docs?

### ISSUE THREAD

**Issue by misterfish** [mirage/ocaml-conduit#398]
Where to access up-to-date documentation for conduit 4.0?

The [Mirage OS docs](https://docs.mirage.io/#name-c) refer to 2.1.0, 2.2.2, and 2.2.1.

**Comment by zshipko** [comment]
It looks like https://mirage.github.io/ocaml-conduit is up to date.

**Comment by dinosaure** [comment]
/cc @avsm, I'm not sure about the state of `docs.mirage.io`. I know that something is currently into the pipe to improve the documentation experience of OCaml projects but I don't know if we will update the website soon. However, as @zshipko said, https://mirage.github.io/ocaml-conduit is up to date.

I will update the README.md to point to this website instead of `docs.mirage.io`. Thanks for your report.

**Comment by dinosaure** [comment]
Updated via 959f57a
