### ISSUE TITLE
Getting an endp for a ws:// uri

### ISSUE THREAD

**Issue by zoggy** [mirage/ocaml-conduit#79]
Hello,

I don't understand how to get an endp value for an uri with scheme `ws://`. Could you provide an example ?

Using `Resolver_lwt_unix.system (Uri.of_string "ws://localhost:8080")`, I get a `Failure("resolution failed: unknown scheme")`.

**Comment by vbmithr** [comment]
Use `https://` instead.

**Comment by avsm** [comment]
Woops, I missed this bug when it was created.  We could also add in a default mapping for `ws://` so that it resolves to a TLS connection as well.

**Comment by dsheets** [comment]
I think `wss://` is the TLS-secured variant.

**Comment by zoggy** [comment]
Indeed, it would be great to support `ws://` and `wss://` .

**Comment by avsm** [comment]
The reason that this fails on the Unix conduit is that `/etc/services` (as used by `getservbyname`) has no entries for `wss` or `ws`

**Comment by vbmithr** [comment]
Yeah, that's why I stopped using those schemes, since they are equal to http/s.

**Comment by dinosaure** [comment]
According to the new version of `conduit`, the issue seems unrelated now - due to the new resolution mechanism which requires a domain-name now. We don't filter protocols by scheme now - and it should be done by an other higher library on top of `conduit`. I will close this issue but if you think that we should resolve `Uri.t` and filter by scheme, you are free to open an other issue :+1:.
