### ISSUE TITLE
Conduit_mirage combinators are order dependent

### ISSUE THREAD

**Issue by Drup** [mirage/ocaml-conduit#93]
Tcp must be done before tls, the other way will give you an error message. It doesn't seem to be documented, so I guess it's not completely on purpose.

(It was very annoying to debug)

**Comment by talex5** [comment]
What is the error message?

**Comment by Drup** [comment]
https://github.com/mirage/ocaml-conduit/blob/b9b8e104b82abcf4d18fa90b5c24005677c5359f/lib/conduit_mirage.ml#L26

**Comment by dinosaure** [comment]
This issue is a mix between `functoria`, how `conduit` is described by `functoria` and how we can fill the `conduit`'s context according what `functoria` gives to us (TCP impl., TLS impl., etc.). I will not close this issue but a possible response to fix this issue was updated by the new release of `conduit`. You should start to figure out **how to properly integrate the new version of `conduit` into `functoria`**.

**Comment by samoht** [comment]
conduit-mirage.4.0  now use functors so this is not an issue anymore.
