### ISSUE TITLE
Documentation and examples on using conduit

### ISSUE THREAD

**Issue by amirmc** [mirage/ocaml-conduit#99]
Over on https://github.com/mirage/mirage/issues/474 @wmhaddad has asked for some docs (and examples) on how to use `conduit`.  From the last MirageOS call, this (and `vchan`) are important components of the work he's doing.

If anyone can help out or point to existing material, that would be useful.

**Comment by talex5** [comment]
There's an interactive notebook explaining VChan here:

http://djs55.github.io/ocaml-vchan/#

**Comment by talex5** [comment]
I wouldn't mind some conduit docs too. The README seems to suggest it's just to abstract over SSL backend, but it seems to do other things too (e.g. vchan vs tcp).

One thing that particularly confuses me is that we have both Unix and Mirage implementations, yet Mirage also supports Unix itself. So on Unix, should I use `Conduit_mirage` with Mirage's Unix stack, or should I use `Conduit_lwt_unix`?

Looks like if I want the option of using ssl (rather than tls) then I need to use `Conduit_lwt_unix`. But if I want to pass TLS configuration as typed values rather than paths then I should use `Conduit_mirage`.

**Comment by dinosaure** [comment]
According to the new version of `conduit` and from feedbacks of some users, it seems that we _fix_ the problem of the documentation - we have [a full documentation](https://github.com/mirage/ocaml-conduit/blob/master/src/core/conduit.mli) of `conduit` with examples. May be we surely miss a _HOW-TO_ but [my](https://blog.x25519.net/2020-09-04--blog.html) [article](https://blog.x25519.net/2020-02-27--tuyau.html) can help. I will close the issue but if you think that materials (documentation, article, etc.) are not enough to understand `conduit`, feel free to re-open the issue.
